### ISSUE TITLE
Use Jekyll

### ISSUE THREAD

**Issue by wooseopkim** [boysnextdoor/78thmove#1]
The famous static site generator written in Ruby: https://jekyllrb.com/

**Comment by linterpreteur** [comment]
More *hip* alternative: [Hugo](http://gohugo.io)

**Comment by linterpreteur** [comment]
Nope, Mustache. Maybe [PHP](https://github.com/bobthecow/mustache.php/wiki), because PHP is awesome and always right.

**Comment by wooseopkim** [comment]
The whole project is being transformed to be a dynamic site.
